// This file is generated by scripts/generate-story-content.mjs

export type StorySlug = "sumnima-chitwan" | "gender-insights-impact" | "dhading-fish-farming" | "sdg-innovation-award";

export type StoryBlock =
  | {
      type: "heading";
      level: 2 | 3;
      html: string;
    }
  | {
      type: "paragraph";
      html: string;
    }
  | {
      type: "list";
      items: ReadonlyArray<string>;
    }
  | {
      type: "image";
      src: string;
      alt: string;
      width: number;
      height: number;
    };

export type StoryArticle = {
  slug: StorySlug;
  category: string;
  date: string;
  title: string;
  description: string;
  sourceDoc: string;
  blocks: ReadonlyArray<StoryBlock>;
};

export const storyArticles = {
  "sumnima-chitwan": {
    "slug": "sumnima-chitwan",
    "category": "Farmer story",
    "date": "August 2025",
    "title": "Her Farm, Her Strength: How Sumnima is building a more secure future in Chitwan",
    "description": "Through a project in Chitwan, SFFI trained 250 farmers and provided microfinance grants to women farmers, helping expand both skills and opportunity. For Sumnima, 28, that support is now helping transform fish farming into a more reliable livelihood and a stronger foundation for her family’s future.",
    "sourceDoc": "/content/stories/sumnima-chitwan.docx",
    "blocks": [
      {
        "type": "image",
        "src": "/images/stories/sumnima-chitwan/hero.jpg",
        "alt": "Sumnima holds a basket of fish on a riverbank in Chitwan, Nepal.",
        "width": 1536,
        "height": 1024
      },
      {
        "type": "paragraph",
        "html": "<strong>“This program gave me more than training. It gave me a way to earn, support my family, and believe that I could build something of my own.”</strong><br /> — <strong>Sumnima, Chitwan</strong>"
      },
      {
        "type": "paragraph",
        "html": "It is early morning in a village in <strong>Chitwan, Nepal</strong>, and the first light has just spread across <strong>28-year-old Sumnima’s</strong> home. The day has only begun, but Sumnima is already at work, moving steadily through the pond and surrounding area that now help sustain her family. Her mornings, like so much of her life, are shaped by care, labor, and responsibility. There is little room for delay when a family depends on what a day’s work can provide."
      },
      {
        "type": "paragraph",
        "html": "As she tends to the fish farming work that has become central to her livelihood, she also sees something that has become deeply important to her: a source of income she can rely on. It is not only the fish pond itself, or the labor it requires, that matters. It is what the work now makes possible. The income she earns is helping her provide for her family, meet household needs with greater confidence, and build a more stable path forward."
      },
      {
        "type": "paragraph",
        "html": "For Sumnima, fish farming is more than a livelihood. It is a way of carrying her family forward."
      },
      {
        "type": "paragraph",
        "html": "That shift did not happen on its own. It grew out of support designed to meet rural women where they are: hardworking, capable, and full of potential, but too often under-supported when it comes to the tools, knowledge, and capital needed to build a stronger economic future."
      },
      {
        "type": "paragraph",
        "html": "Through a project in <strong>Chitwan</strong>, the <strong>Sustainable Fish Farming Initiative (SFFI)</strong> trained <strong>250 farmers</strong> and provided <strong>microfinance grants to women farmers</strong>, helping expand both the technical knowledge and financial support needed to make fish farming a more viable livelihood. For women like Sumnima, that combination mattered. Training provided the practical skills. Microfinance made it possible to act on them."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>A livelihood built on more than effort</strong>"
      },
      {
        "type": "paragraph",
        "html": "For many women in rural communities, the barrier is not determination. It is access."
      },
      {
        "type": "paragraph",
        "html": "A woman may have the discipline to build a livelihood, the willingness to work, and the daily responsibility of caring for a family, yet still be held back by limited capital, too few opportunities, and a lack of support at the exact moment it is needed most. She may know how important income is. She may understand what her family needs. But without technical guidance, financial support, or a pathway to begin, that knowledge alone does not always become opportunity."
      },
      {
        "type": "paragraph",
        "html": "That is why SFFI’s work in Chitwan was designed to support women farmers more fully."
      },
      {
        "type": "paragraph",
        "html": "The project combined practical fish farming training with microfinance grants, helping women gain both the skills and the financial foundation needed to begin, strengthen, or expand their work. Farmers were trained in key areas of aquaculture, including <strong>pond preparation, stocking, feeding, routine maintenance, and the day-to-day management needed to improve productivity and reduce avoidable losses</strong>. This was not training built around theory alone. It was built around the realities of smallholder life — the realities of limited resources, careful decisions, and the need to make each effort count."
      },
      {
        "type": "paragraph",
        "html": "For Sumnima, this support became a turning point."
      },
      {
        "type": "paragraph",
        "html": "The revenue she now earns through the program is helping her care for her family and meet household needs with greater confidence. In practical terms, that means more stability around essentials: food at home, day-to-day expenses, and the ongoing pressures that shape family life. What once may have felt uncertain now carries more structure, more predictability, and more possibility."
      },
      {
        "type": "paragraph",
        "html": "That kind of change matters deeply. In rural households, even modest increases in stability can transform how a family experiences the future. Daily life becomes a little less fragile. Financial decisions feel a little less impossible. And the work a woman does begins to return not only income, but confidence."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>When women earn, the impact extends beyond income</strong>"
      },
      {
        "type": "paragraph",
        "html": "A stronger livelihood for a woman rarely affects only one person."
      },
      {
        "type": "paragraph",
        "html": "It moves through the household. It shapes whether there is food at home, whether daily needs can be met more reliably, and whether life feels a little less exposed to disruption. It can ease the pressure that families carry from one week to the next. It can create more room to plan, more space to breathe, and more reason to believe that hard work can lead to something steadier."
      },
      {
        "type": "paragraph",
        "html": "That is part of what makes Sumnima’s story so important."
      },
      {
        "type": "paragraph",
        "html": "Her progress reflects a larger truth that development work too often understates: when women are trusted with both knowledge and investment, the benefits extend far beyond income alone. They strengthen households. They improve resilience. They build confidence. And they contribute to a more secure future for entire families."
      },
      {
        "type": "paragraph",
        "html": "For women in rural communities, livelihood is never only about earning. It is also about care. It is about whether children’s needs can be met, whether there is enough food in the home, whether emergencies feel survivable, and whether tomorrow seems a little less uncertain than today. When a woman’s economic footing becomes stronger, the emotional and material life of the household often shifts with it."
      },
      {
        "type": "paragraph",
        "html": "In that sense, Sumnima’s story is not just about a woman earning from fish farming. It is about a woman helping stabilize the world around her."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>Why this model matters</strong>"
      },
      {
        "type": "paragraph",
        "html": "The Chitwan project reached <strong>250 farmers</strong>, but its significance is not only in the number."
      },
      {
        "type": "paragraph",
        "html": "What matters is that the project recognized something essential about rural livelihoods: <strong>training by itself is not always enough, and finance by itself is not always enough</strong>. Knowledge without capital can leave women prepared but unable to move. Capital without knowledge can create risk without stability. But when the two are combined, the path from learning to livelihood becomes far more real."
      },
      {
        "type": "paragraph",
        "html": "That is what SFFI helped create in Chitwan."
      },
      {
        "type": "paragraph",
        "html": "By pairing technical fish farming training with microfinance grants for women farmers, the program gave women a stronger chance to translate effort into income, and income into greater household security. It treated women not as passive recipients of support, but as economic actors capable of building, managing, and growing livelihoods of their own when given the right foundation."
      },
      {
        "type": "paragraph",
        "html": "That distinction matters. Too often, rural women are expected to carry enormous responsibility without receiving equal access to productive resources. They are central to family wellbeing, yet frequently peripheral in the design of livelihood systems. Programs like this matter because they begin to correct that imbalance. They create entry points for women to participate more fully, earn more directly, and shape the future of their households with greater agency."
      },
      {
        "type": "paragraph",
        "html": "For Sumnima, that support is no longer abstract. It is visible in the life she is building."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>A future taking shape, one day at a time</strong>"
      },
      {
        "type": "paragraph",
        "html": "Sumnima’s story is, at its heart, a story about agency."
      },
      {
        "type": "paragraph",
        "html": "It is about what becomes possible when a woman is not only willing to work, but is given the tools and support to build something that can last. It is about a livelihood becoming more than a source of income. It becomes a source of dignity. A source of stability. A source of hope."
      },
      {
        "type": "paragraph",
        "html": "At 28, Sumnima is helping shape that future for her family through the revenue she now earns from fish farming. The work is still demanding. The responsibility is still great. The days are still long. But the future she is building is no longer defined only by limitation."
      },
      {
        "type": "paragraph",
        "html": "It is being shaped by opportunity, persistence, and the strength of a woman building something of her own."
      },
      {
        "type": "paragraph",
        "html": "And that may be the most important part of this story."
      },
      {
        "type": "paragraph",
        "html": "Not only that Sumnima is earning.<br /> Not only that she is working.<br /> But that her work is creating something steadier beneath her family’s life — a stronger foundation, a more reliable livelihood, and a future shaped not only by hardship, but by possibility."
      },
      {
        "type": "paragraph",
        "html": "In Chitwan, that future is still taking shape. It is still being built through daily effort, careful choices, and the quiet determination that often goes unseen. But it is real. And in households like Sumnima’s, it is already making a difference."
      }
    ]
  },
  "gender-insights-impact": {
    "slug": "gender-insights-impact",
    "category": "Research",
    "date": "May 2025",
    "title": "From data to impact: How gender insights help farmers prosper",
    "description": "Gender-responsive learning helped SFFI see where women were still facing barriers in fish farming and how better-targeted support could improve outcomes. In Nepal, this approach strengthened the connection between technical training, women-centered finance, stronger livelihoods, and more secure households.",
    "sourceDoc": "/content/stories/gender-insights.docx",
    "blocks": [
      {
        "type": "image",
        "src": "/images/stories/gender-insights-impact/hero.jpg",
        "alt": "A woman crouches on a wooden boat while pulling a fish from a net.",
        "width": 1536,
        "height": 1024
      },
      {
        "type": "paragraph",
        "html": "<strong>When gender gaps were better understood, support became more targeted, more practical, and more effective.</strong>"
      },
      {
        "type": "paragraph",
        "html": "Closing gender gaps started with understanding where they persisted, how they shaped livelihoods, and what kinds of interventions shifted outcomes."
      },
      {
        "type": "paragraph",
        "html": "In Nepal, women made up more than half of the country’s farmers, yet only around one-third owned farmland. At the same time, high levels of child stunting continued to underline the need for livelihood models that strengthened both incomes and diets. Against that backdrop, aquaculture became increasingly relevant—not only as a source of income, but as part of a broader pathway toward food security, resilience, and women’s economic empowerment."
      },
      {
        "type": "paragraph",
        "html": "For Sustainable Fish Farming Initiative, that reality shaped both the design of its work and the way it measured progress. In Baseri Village, Dhading, the initiative delivered 20 technical training sessions reaching 300 farmers. In Chitwan, it trained 250 farmers and provided microfinance grants to women farmers. These experiences showed that when technical support was paired with women-centered financing and locally rooted delivery, fish farming could contribute to stronger livelihoods and improved household wellbeing."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>How we collected gender data</strong>"
      },
      {
        "type": "paragraph",
        "html": "Gender-responsive monitoring, evaluation, and learning served as more than a reporting function. It helped reveal whether women were not only participating, but also benefiting in meaningful ways."
      },
      {
        "type": "paragraph",
        "html": "That distinction mattered in rural Nepal, where women’s labor remained central to agriculture while access to productive assets, finance, and decision-making power often remained unequal. Measuring attendance alone could not capture that reality. What mattered was whether women were able to translate participation into productivity, income, agency, and improved wellbeing at household level."
      },
      {
        "type": "paragraph",
        "html": "The initiative’s learning approach therefore focused on two connected questions: whether women and men experienced different outcomes in fish farming, and whether women’s agency strengthened through participation in the program."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>Track 1: Gender-disaggregated productivity &amp; income</strong>"
      },
      {
        "type": "paragraph",
        "html": "The first track focused on productivity and income."
      },
      {
        "type": "paragraph",
        "html": "In aquaculture, as in much of agriculture, productive activity often took place at household level. That meant it was not enough to record who attended training sessions or who was listed as a participant. It was also necessary to understand who made decisions about pond preparation, stocking, feeding, harvesting, marketing, and the use of income from fish sales."
      },
      {
        "type": "paragraph",
        "html": "Tracking these dynamics helped bring hidden inequalities into view. It showed where women faced constraints in entering fish farming, adopting improved practices, or benefiting equitably from the returns generated. It also helped identify which forms of support were most effective in moving women from participation to measurable livelihood gains."
      },
      {
        "type": "paragraph",
        "html": "This mattered because women’s involvement in agriculture did not automatically translate into control over productive outcomes. When women had access to training but lacked access to land, ponds, capital, or authority over enterprise decisions, the impact of programming remained limited. Gender-disaggregated learning helped make those constraints visible and actionable."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>Track 2: Women’s empowerment &amp; agency</strong>"
      },
      {
        "type": "paragraph",
        "html": "The second track focused on women’s empowerment and agency."
      },
      {
        "type": "paragraph",
        "html": "Productivity mattered, but development outcomes became stronger and more durable when women were able to make and act on decisions that affected their livelihoods and their households. This meant paying attention not only to income gains, but also to questions of influence and control: whether women had a say in production decisions, whether they participated in decisions about sales and household spending, whether they had sole or joint control over productive assets, and whether enterprise activity strengthened their confidence and economic standing."
      },
      {
        "type": "paragraph",
        "html": "The importance of this was already visible in field experience. In Baseri, Mandira, a 35-year-old single mother of five, used training to start her own fish farm and reportedly increased household income by 90 percent. In Chitwan, Sumnima, age 28, helped support her family through income earned from the program. These were individual cases rather than portfolio-wide claims, but they pointed to a broader lesson: women’s agency was visible not only in participation, but in enterprise decisions, income use, and household wellbeing."
      },
      {
        "type": "paragraph",
        "html": "<strong>Women’s empowerment was not treated as a secondary outcome. It was central to how impact was understood.</strong>"
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>Using insights to drive change</strong>"
      },
      {
        "type": "paragraph",
        "html": "The purpose of collecting gender data was not to produce better dashboards. It was to improve decisions."
      },
      {
        "type": "paragraph",
        "html": "When data showed that women attended fewer trainings because schedules conflicted with care responsibilities, outreach methods and delivery times were adjusted. When women completed training but could not establish ponds because of capital constraints, women-centered finance mechanisms were strengthened. When women contributed substantially to pond management but had limited influence over sales and income use, the program incorporated stronger support for household dialogue and shared decision-making."
      },
      {
        "type": "paragraph",
        "html": "This was where gender-responsive learning moved from observation to action. By linking participation data with evidence on productivity, income, and agency, the initiative identified which combinations of training, finance, and community engagement produced stronger outcomes for women farmers."
      },
      {
        "type": "paragraph",
        "html": "That shift mattered in a country where aquaculture continued to grow, fish became an increasingly important source of animal protein, and women already formed a large share of the agricultural workforce. Better data helped bridge the gap between participation and equitable benefit by showing where inequalities persisted and what kinds of program responses were most likely to reduce them."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>Looking ahead</strong>"
      },
      {
        "type": "paragraph",
        "html": "The experience in Nepal showed that sustainable fish farming could do more than generate income. It could help strengthen diets, diversify livelihoods, expand women’s economic participation, and build resilience at household level."
      },
      {
        "type": "paragraph",
        "html": "The opportunity, therefore, was not simply to scale activity, but to strengthen the evidence behind it. That meant treating gender data as core program infrastructure: essential to design, implementation, learning, and accountability. It meant measuring not only how many women were reached, but whether productivity improved, incomes grew, agency expanded, and households became more secure as a result."
      },
      {
        "type": "paragraph",
        "html": "When that happened, gender-responsive aquaculture was no longer a niche intervention. It became part of a broader rural transformation agenda."
      },
      {
        "type": "paragraph",
        "html": "Because when women farmers prospered, households became more secure, communities became more resilient, and development impact became more durable."
      }
    ]
  },
  "dhading-fish-farming": {
    "slug": "dhading-fish-farming",
    "category": "Field update",
    "date": "April 2024",
    "title": "Fish Farming in Dhading Is Strengthening Rural Livelihoods",
    "description": "In Baseri Village, Dhading, SFFI delivered 20 technical trainings reaching 500 farmers, helping rural households strengthen fish farming as a pathway to improved nutrition, more stable income, and greater resilience. Rooted in practical, community-based learning, the project equipped farmers with the skills to improve productivity and reduce risk. For women like Mandira, a single mother of five, that support helped launch a new livelihood and increase household income by 90%.",
    "sourceDoc": "/content/stories/dhading-fish-farming.docx",
    "blocks": [
      {
        "type": "image",
        "src": "/images/stories/dhading-fish-farming/hero.jpg",
        "alt": "Mandira stands beside a fish pond in Baseri Village, Dhading.",
        "width": 1536,
        "height": 1024
      },
      {
        "type": "paragraph",
        "html": " <em>“Before this, I was always worried about how I would provide for my children. Starting my own fish farm has changed that. My income has increased, I can care for my family with more confidence, and I feel proud that I am building a better future for my children with my own hands.”</em><br /> — <strong>Mandira, Baseri Village, Dhading</strong>"
      },
      {
        "type": "paragraph",
        "html": "In Baseri Village, Dhading, many families live with a narrow margin for error. A poor harvest, rising food prices, illness, or the loss of income can quickly place a household under strain. In this context, food insecurity is not only about what is missing today. It is about how fragile tomorrow can feel."
      },
      {
        "type": "paragraph",
        "html": "That is the reality Sustainable Fish Farming Initiative is working to change."
      },
      {
        "type": "paragraph",
        "html": "Through a focused field project in Baseri Village, SFFI delivered <strong>20 technical training sessions reaching 500 farmers</strong>, helping rural households strengthen fish farming as a practical pathway to improved nutrition, more stable income, and greater resilience over time."
      },
      {
        "type": "paragraph",
        "html": "The project was designed around a simple but important principle: when farmers have access to practical knowledge, locally relevant support, and skills they can use immediately, they are better equipped to build livelihoods that hold."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>A practical approach to rural resilience</strong>"
      },
      {
        "type": "paragraph",
        "html": "Fish farming can play a meaningful role in rural livelihoods when it is supported well. For households in Dhading, it offers more than one benefit. It can improve access to nutrient-rich food, create additional income opportunities, and provide a productive asset that grows over time."
      },
      {
        "type": "paragraph",
        "html": "But success in fish farming does not happen automatically. It depends on technical knowledge, sound management, and the confidence to apply that knowledge under real conditions."
      },
      {
        "type": "paragraph",
        "html": "That is why SFFI’s field trainings focused on the practical foundations of smallholder aquaculture, including:"
      },
      {
        "type": "list",
        "items": [
          "pond preparation and embankment maintenance",
          "pond conditioning and liming",
          "healthy stocking practices",
          "feed timing and ration management",
          "water quality awareness",
          "routine pond monitoring and fish health observation",
          "harvest planning for both home consumption and local sale"
        ]
      },
      {
        "type": "paragraph",
        "html": "These were not abstract sessions. They were designed for the conditions farmers in Baseri Village actually face: limited capital, time pressure, variable water conditions, and the need to make each livelihood decision count."
      },
      {
        "type": "paragraph",
        "html": "With <strong>500 farmers reached across 20 trainings</strong>, the project combined scale with practical learning, creating space for direct participation while ensuring that technical knowledge remained usable and rooted in local realities."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>When knowledge becomes opportunity</strong>"
      },
      {
        "type": "paragraph",
        "html": "At the heart of this work is a simple belief: rural families do not lack determination. Too often, they lack access to the right tools, information, and support systems. When that gap begins to close, the results can be transformative."
      },
      {
        "type": "paragraph",
        "html": "For <strong>Mandira, 35, a single mother of five children</strong>, the training became more than a learning opportunity. It became the beginning of a new livelihood."
      },
      {
        "type": "paragraph",
        "html": "Before joining the project, Mandira was supporting her family under difficult conditions, carrying the daily pressure of providing food, care, and financial stability for her children. Through the training, she gained practical knowledge in pond preparation, stocking, feeding, and day-to-day fish farm management. With that knowledge, she took a significant step forward: she started <strong>her own fish farming enterprise</strong>."
      },
      {
        "type": "paragraph",
        "html": "Since then, Mandira’s household has seen a <strong>90% increase in income</strong>."
      },
      {
        "type": "paragraph",
        "html": "Her story reflects what this project is ultimately about. Not only better production. Not only improved technical practice. But the possibility of turning knowledge into agency, and agency into lasting change."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>Building stronger livelihoods from the ground up</strong>"
      },
      {
        "type": "paragraph",
        "html": "The significance of this project lies not only in the number of farmers reached, but in where the knowledge was placed: directly in the hands of rural producers."
      },
      {
        "type": "paragraph",
        "html": "When farmers understand how to prepare ponds properly, manage inputs more carefully, monitor fish health, and reduce avoidable losses, they are better able to turn effort into stronger results. When women gain access to those same skills and opportunities, the effects often extend beyond income to food security, household confidence, and long-term stability."
      },
      {
        "type": "paragraph",
        "html": "That is especially important in communities where livelihoods are fragile and opportunity is unevenly distributed. In these settings, diversification is not a luxury. It is a form of protection. A stronger pond can mean a stronger household. A stronger household can mean children with better nutrition, more stability, and more room to hope."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>What this update shows</strong>"
      },
      {
        "type": "paragraph",
        "html": "This field project in Baseri Village points to something important: practical, community-rooted training can help families build more resilient futures."
      },
      {
        "type": "paragraph",
        "html": "Through <strong>20 technical trainings reaching 500 farmers</strong>, SFFI is helping strengthen fish farming as a viable livelihood strategy in Dhading. And for women like Mandira, that support is already translating into measurable change."
      },
      {
        "type": "paragraph",
        "html": "There is still much work ahead. But in Baseri Village, the foundation is being laid carefully and locally — farmer by farmer, household by household, season by season."
      },
      {
        "type": "paragraph",
        "html": "That is what progress looks like in practice."
      }
    ]
  },
  "sdg-innovation-award": {
    "slug": "sdg-innovation-award",
    "category": "Award feature",
    "date": "August 2024",
    "title": "Cultivating Change: SFFI’s SDG Innovation Award for Sustainable Aquaculture",
    "description": "SFFI’s SDG Innovation Award for Sustainable Aquaculture was created to honor grassroots innovators shaping a more sustainable, inclusive, and resilient future for aquaculture in Nepal. By recognizing community-rooted leadership, the award helped amplify ideas that were advancing food systems, livelihoods, and youth-led innovation.",
    "sourceDoc": "/content/stories/sdg-award.docx",
    "blocks": [
      {
        "type": "paragraph",
        "html": "<strong><em>Recognizing the grassroots innovators helping shape a more sustainable, inclusive, and resilient future for aquaculture in Nepal.</em></strong>"
      },
      {
        "type": "image",
        "src": "/images/stories/sdg-innovation-award/hero.jpg",
        "alt": "Award recipients and supporters pose with SDG Innovation Award checks and certificates.",
        "width": 2048,
        "height": 1365
      },
      {
        "type": "paragraph",
        "html": "The <strong>Sustainable Fish Farming Initiative (SFFI) SDG Innovation Award for Sustainable Aquaculture</strong> was created to do more than recognize promising ideas. It was designed to spotlight grassroots innovators whose work was advancing sustainable aquaculture, strengthening rural livelihoods, and opening new pathways for youth-led innovation in Nepal."
      },
      {
        "type": "paragraph",
        "html": "At its heart, the award reflected a simple but important belief: local innovation mattered. Across Nepal, some of the most practical and inspiring solutions were emerging not from large institutions, but from entrepreneurs, farmers, and community-rooted changemakers responding directly to the challenges around them."
      },
      {
        "type": "paragraph",
        "html": "<strong>“The award was not only about recognition. It was about creating visibility, momentum, and support for ideas with real community impact.”</strong>"
      },
      {
        "type": "paragraph",
        "html": "By honoring fellows each year, SFFI helped bring wider attention to innovations that might otherwise have remained local. The award also created space for connection across agriculture, aquaculture, entrepreneurship, and youth leadership—showing how sustainable fish farming could contribute to wider development goals, from food security to inclusive economic opportunity."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>Why the award mattered</strong>"
      },
      {
        "type": "paragraph",
        "html": "Nepal’s agricultural future depended not only on policy and investment, but also on the people testing new ideas on the ground. Yet many grassroots innovators faced a familiar challenge: they had strong solutions, but limited access to public recognition, networks, and platforms that could help them grow."
      },
      {
        "type": "paragraph",
        "html": "SFFI’s yearly award responded to that gap. It recognized leadership in sustainable aquaculture, encouraged practical and environmentally responsible innovation, and supported young changemakers working to improve food production, resource efficiency, and livelihoods in their communities."
      },
      {
        "type": "paragraph",
        "html": "In this sense, the award was as much about building a culture of innovation as it was about celebrating individual achievement."
      },
      {
        "type": "paragraph",
        "html": "<strong>“Sustainable aquaculture becomes more powerful when local innovators are seen, supported, and connected.”</strong>"
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>The winners</strong>"
      },
      {
        "type": "paragraph",
        "html": "One of the most notable editions of the award came in <strong>2018</strong>, when SFFI recognized a cohort of Nepali innovators whose work combined technical creativity with strong social purpose."
      },
      {
        "type": "paragraph",
        "html": "The fellowship award was presented during the <strong>2nd Youth Agriculture Entrepreneurship Symposium</strong>, hosted by <strong>4-H Nepal</strong> in collaboration with <strong>SFFI, Ayon Nepal, National Youth Council Nepal, Youth Action Nepal, and FIAN Nepal</strong>, among others. The symposium brought together nearly <strong>200 young Nepali agriculture enthusiasts</strong> and concluded with a <strong>15-point declaration</strong>, reflecting the energy of a new generation of agricultural leadership."
      },
      {
        "type": "heading",
        "level": 3,
        "html": "<strong>Rita Shrestha Bhadra – Aquaponics Nepal</strong>"
      },
      {
        "type": "image",
        "src": "/images/stories/sdg-innovation-award/image-1.jpg",
        "alt": "Rita Shrestha Bhadra holds an SDG Innovation Award check and certificate for Aquaponics Nepal.",
        "width": 2048,
        "height": 1365
      },
      {
        "type": "paragraph",
        "html": "Rita Shrestha Bhadra, founder of <strong>Aquaponics Nepal</strong>, was honored for pioneering aquaponics as a sustainable farming solution in Kathmandu."
      },
      {
        "type": "paragraph",
        "html": "Her work introduced an innovative model of year-round food production that used significantly less water than conventional farming while integrating fish production with plant cultivation. She also extended her impact through training, including work with <strong>80 women participants from Budhanilkantha Ward 9</strong>, and brought a strong commitment to expanding women’s participation in aquaculture."
      },
      {
        "type": "heading",
        "level": 3,
        "html": "<strong>Ashok Adhikari – Krishi Guru</strong>"
      },
      {
        "type": "image",
        "src": "/images/stories/sdg-innovation-award/image-2.jpg",
        "alt": "Ashok Adhikari holds an SDG Innovation Award check and certificate.",
        "width": 2048,
        "height": 1365
      },
      {
        "type": "paragraph",
        "html": "Ashok Adhikari was recognized for his long-standing commitment to Nepal’s aquaculture sector and his efforts to use digital tools to improve the livelihoods of fish farmers."
      },
      {
        "type": "paragraph",
        "html": "Through his association with <strong>Krishi Guru</strong>, a mobile-based agriculture knowledge-sharing platform, he helped connect farmers to extension agencies, input suppliers, agro-entrepreneurs, and market traders. His work demonstrated how technology, knowledge, and better access to information could support more productive and profitable aquaculture systems."
      },
      {
        "type": "heading",
        "level": 3,
        "html": "<strong>Om Thapa and Tara Thapa – Galyang Aquaponics Farm</strong>"
      },
      {
        "type": "image",
        "src": "/images/stories/sdg-innovation-award/image-3.jpg",
        "alt": "Om Thapa and Tara Thapa hold an SDG Innovation Award check and framed certificate for Galyang Aquaponics Farm.",
        "width": 2048,
        "height": 1365
      },
      {
        "type": "paragraph",
        "html": "Om Thapa and Tara Thapa, co-founders of <strong>Galyang Aquaponics Farm</strong> in Syangja, were recognized for building an innovative aquaponics system that combined fish farming with vegetable production."
      },
      {
        "type": "paragraph",
        "html": "Their work offered a practical example of how resource-efficient farming could respond to land constraints, food needs, and the growing importance of sustainable local production. By adapting new techniques to local conditions, they showed how innovation could thrive at community level."
      },
      {
        "type": "heading",
        "level": 2,
        "html": "<strong>More than an award</strong>"
      },
      {
        "type": "paragraph",
        "html": "Taken together, the 2018 winners reflected the wide range of change SFFI sought to support: digital extension, women-led entrepreneurship, aquaponics innovation, and community-based food system transformation."
      },
      {
        "type": "paragraph",
        "html": "The SDG Innovation Award for Sustainable Aquaculture stood for more than celebration. It affirmed that sustainable aquaculture in Nepal would be shaped not only by institutions, but by the vision, determination, and creativity of local innovators."
      },
      {
        "type": "paragraph",
        "html": "<strong>“When grassroots innovators are recognized and supported, their ideas travel farther and their impact grows deeper.”</strong>"
      },
      {
        "type": "paragraph",
        "html": "That remained the reason behind the award each year: to identify promising leaders, amplify their work, and help build a stronger future for sustainable aquaculture in Nepal."
      }
    ]
  }
} as const satisfies Record<StorySlug, StoryArticle>;

export const storyArticleSlugs = Object.keys(storyArticles) as StorySlug[];
